import fs from "node:fs";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const recordDir = path.join(projectRoot, "docs", "test-records");
const workRecordDir = path.join(projectRoot, "work", "test-records");
const pnpm = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
const startedAt = new Date().toISOString();
const checks = [];

function runCommand(id, title, args) {
  const started = Date.now();
  const result = spawnSync(pnpm, args, {
    cwd: projectRoot,
    encoding: "utf8",
    windowsHide: true,
    shell: process.platform === "win32",
    env: { ...process.env, FORCE_COLOR: "0" },
  });
  const output = `${result.stdout ?? ""}\n${result.stderr ?? ""}\n${result.error?.message ?? ""}`.trim();
  const check = {
    id,
    title,
    command: `pnpm ${args.join(" ")}`,
    status: result.status === 0 ? "PASS" : "FAIL",
    exitCode: result.status,
    durationMs: Date.now() - started,
    outputTail: output.slice(-500),
  };
  checks.push(check);
  return result.status === 0;
}

async function waitForApp(url, child) {
  for (let attempt = 0; attempt < 45; attempt += 1) {
    try {
      const response = await fetch(`${url}/api/events`);
      if (response.ok || response.status === 401) return true;
    } catch {
      // The server is still starting.
    }
    await new Promise((resolve) => setTimeout(resolve, 1000));
    if (child.exitCode !== null) return false;
  }
  return false;
}

function readSuite(name) {
  const file = path.join(workRecordDir, `${name}-latest.json`);
  if (!fs.existsSync(file)) return null;
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function markdownCell(value) {
  return String(value ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
}

function writeAggregate(record) {
  fs.mkdirSync(recordDir, { recursive: true });
  const jsonPath = path.join(recordDir, "latest.json");
  const markdownPath = path.join(recordDir, "latest.md");
  fs.writeFileSync(jsonPath, `${JSON.stringify(record, null, 2)}\n`);

  const checkRows = record.checks
    .map((item) => `| ${item.id} | ${markdownCell(item.title)} | ${item.status} | ${item.durationMs} ms | ${markdownCell(item.command)} |`)
    .join("\n");
  const suiteRows = record.suites
    .flatMap((suite) => suite?.cases ?? [])
    .map((item) => `| ${item.id} | ${markdownCell(item.title)} | ${item.status} | ${item.durationMs} ms | ${markdownCell(item.expected)} | ${markdownCell(item.actual)} |`)
    .join("\n");
  const status = record.status === "PASSED" ? "PASSED" : "FAILED";
  const markdown = [
    "# Gatherly complete test record",
    "",
    `- Status: **${status}**`,
    `- Started: ${record.startedAt}`,
    `- Finished: ${record.finishedAt}`,
    "- This file is generated by `pnpm test:record`.",
    "",
    "## Command checks",
    "",
    "| ID | Check | Result | Duration | Command |",
    "| --- | --- | --- | ---: | --- |",
    checkRows || "| — | No command checks recorded | — | — | — |",
    "",
    "## Individual test cases",
    "",
    "| ID | Test case | Result | Duration | Expected | Actual |",
    "| --- | --- | --- | ---: | --- | --- |",
    suiteRows || "| — | No individual cases recorded | — | — | — | — |",
    "",
    "## Evidence files",
    "",
    "- Business rule detail: `work/test-records/gatherly-business-rules-latest.md`",
    "- PRD acceptance detail: `work/test-records/gatherly-prd-acceptance-cases-latest.md`",
    "- Existing browser captures: `docs/screenshots/`",
    "",
  ].join("\n");
  fs.writeFileSync(markdownPath, markdown);
}

const typecheckPassed = runCommand("CHK-01", "Strict TypeScript validation", ["typecheck"]);
const rulesPassed = runCommand("CHK-02", "Business rule tests", ["test"]);
const buildPassed = runCommand("CHK-03", "Production build", ["build"]);
const seedPassed = runCommand("CHK-04", "Reset local demo data for deterministic acceptance fixtures", ["db:seed"]);

let appProcess = null;
let e2ePassed = false;
const localUrl = process.env.TEST_BASE_URL || "http://localhost:3000";
try {
  let appReady = false;
  try {
    const response = await fetch(`${localUrl}/api/events`);
    appReady = response.ok || response.status === 401;
  } catch {
    appReady = false;
  }
  if (!appReady) {
    appProcess = spawn(pnpm, ["start"], {
      cwd: projectRoot,
      windowsHide: true,
      stdio: "ignore",
      shell: process.platform === "win32",
      env: { ...process.env, FORCE_COLOR: "0" },
    });
    appReady = await waitForApp(localUrl, appProcess);
  }
  if (appReady) {
    e2ePassed = runCommand("CHK-05", "Recorded PRD acceptance cases", ["test:e2e"]);
  } else {
    checks.push({ id: "CHK-05", title: "Recorded PRD acceptance cases", command: "pnpm test:e2e", status: "FAIL", exitCode: null, durationMs: 0, outputTail: "Application did not become ready on the test URL." });
  }
} finally {
  if (appProcess) {
    if (process.platform === "win32") {
      spawnSync("taskkill", ["/pid", String(appProcess.pid), "/t", "/f"], { windowsHide: true });
    } else {
      appProcess.kill();
    }
  }
}

const finishedAt = new Date().toISOString();
const suites = [readSuite("gatherly-business-rules"), readSuite("gatherly-prd-acceptance-cases")].filter(Boolean);
const record = {
  project: "Gatherly Event Registration System",
  startedAt,
  finishedAt,
  status: typecheckPassed && rulesPassed && buildPassed && seedPassed && e2ePassed ? "PASSED" : "FAILED",
  checks,
  suites,
  totals: {
    commandChecks: checks.length,
    commandChecksPassed: checks.filter((item) => item.status === "PASS").length,
    individualCases: suites.reduce((total, suite) => total + suite.totals.cases, 0),
    individualCasesPassed: suites.reduce((total, suite) => total + suite.totals.passed, 0),
  },
};
writeAggregate(record);

if (record.status !== "PASSED") process.exitCode = 1;
console.log(`Complete test record written to ${path.relative(projectRoot, path.join(recordDir, "latest.md"))}`);
